# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Donatas Martinkus
email: donatasmart@gmail.com
description:
  Personal webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.donatasmart.lt" # the base hostname & protocol for your site, e.g. http://example.com
author: Donatas Martinkus <donatasmart@gmail.com>
github_username: doncem

google_site_verification: gND_iyudJzru_kmf-YSstX8_FFr7vXAFV8ajx-KbuaM

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
#theme: minima
plugins:
#  - jekyll-assets
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  posts:
    output: true
    permalink: /post/:year/:month/:day/:slug
  projects:

#assets:
#  prefix: "/assets"
#  sources:
#    - _assets
#    - semantic/dist

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
